name: linux

on:
  push:
    branches: '*'

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: List original dotfiles
      run: |
        ls -ld ~/.??*

    - name: Move original dotfiles
      run: |
        for f in .bash??* ; do
          mv $f $f.bak
        done

    - name: Deploy dotfiles
      run: make install-symlink

    - name: Load .bash_profile
      run: |
        cat -n ~/.bash_profile
        echo "==="
        bash ~/.bash_profile 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Load .bashrc
      run: |
        cat -n ~/.bashrc
        echo "==="
        bash -l -c "source ~/.bashrc" 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Run bash login shell
      run: |
        bash -l
        exit

    - name: Install zsh
      run: sudo apt-get --assume-yes install zsh

    - name: Run zsh login shell
      run: |
        zsh -l
        exit
