name: linux

on:
  push:
    branches: '*'

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Debug output
      run: |
        echo "Current directory is $PWD"
        echo "Home directory is $HOME"

    - name: List original dotfiles
      run: |
        ls -ld ~/.??*

    - name: Move original dotfiles
      run: |
        for f in ~/.bash??* ; do
          mv -v $f $f.bak
        done

    - name: Deploy dotfiles
      run: make install-symlink

    - name: Define locale
      run: sudo localedef -f UTF-8 -i ja_JP ja_JP

    - name: Install zsh
      run: sudo apt-get --quiet --assume-yes install zsh

    - name: Run login bash which read .bash_profile and .bashrc
      run: |
        echo "previous SHLVL=$SHLVL"
        bash -l -c 'echo "sub-bash SHLVL=$SHLVL"'
        echo "post SHLVL=$SHLVL"

    - name: Run login zsh which read .zprofile and .zshrc
      run: |
        echo "previous SHLVL=$SHLVL"
        zsh -l -c 'echo "sub-zsh SHLVL=$SHLVL"'
        echo "post SHLVL=$SHLVL"
