name: linux

on:
  push:
    branches: '*'

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy dotfiles
      run: make install-symlink

    - name: Load .bash_profile
      run: |
        bash ~/.bash_profile 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Load .bashrc
      run: |
        cat -n ~/.bashrc
        echo "==="
        bash ~/.bashrc 2> error.log; cat error.log
        if [ -s error.log ]; then false; fi

    - name: Run bash login shell
      run: |
        bash -l
        exit
    - name: Run zsh login shell
      run: |
        zsh -l
        exit
